name: continous integration of user-service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

  services:
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ithunjanthanne
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Add env file to the runner just for testing the database
      run: echo 'TEST_DATABASE_ADDR="host=localhost user=postgres password=ithunjanthanne dbname=test_db sslmode=disable"' > cmd/.env

    - name: Test Database
      run: go test -v ./test/ -run TestDatabaseConnection

    - name: Test
      run: go test -v ./test
